version: '3'

volumes:
  mysql_data:
      driver: local

services:
  postgres:
    image: 'postgres:alpine'
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: 'always'
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
  kc1:
      build: "./keycloak"
      container_name: kc1
      command: start-dev
      environment:
        DB_VENDOR: postgres
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: "true"
        KC_CACHE_CONFIG_FILE: cache-custom.xml
      depends_on:
         - postgres
      ports:
        - "8090:8080"   
  kc2:
      container_name: kc2
      command: start-dev
      build: "./keycloak"
      ports:
        - "8080:8080"
      environment:
        DB_VENDOR: postgres
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: "true"
        KC_CACHE_CONFIG_FILE: cache-custom.xml
      depends_on:
        - postgres
  kc_lb:
    container_name: kc_lb
    build: ./nginx/
    ports:
        - 80:80
    depends_on:
      - kc1
      - kc2
                
  
